name: Build Android APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache git libffi-dev libssl-dev libsqlite3-dev openssl python3-dev zip unzip zlib1g-dev openjdk-17-jdk
          pip install buildozer cython==0.29.33

      - name: Generate Spec File Safely
        run: |
          yes | buildozer init || true
          sed -i 's/#android.permissions = INTERNET/android.permissions = INTERNET/g' buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-apk
          path: bin/*.apk
